apiVersion: v1
kind: Service
metadata:
  name: ratatoskr
  labels:
    app.kubernetes.io/name: ratatoskr
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 3000
      targetPort: http
      protocol: TCP
  selector:
    app.kubernetes.io/name: ratatoskr
